///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class StatisticalTransferReport {
/*
{
  "order_id": "333333333",
  "target_number": "11111111111",
  "source_number": "222222222",
  "money": 10011.6,
  "bank": "ABC",
  "channel": "t1",
  "timestamp": 17337979599248718
} 
*/

  String? orderId;
  String? targetNumber;
  String? sourceNumber;
  double? money;
  String? bank;
  String? channel;
  int? timestamp;

  StatisticalTransferReport({
    this.orderId,
    this.targetNumber,
    this.sourceNumber,
    this.money,
    this.bank,
    this.channel,
    this.timestamp,
  });
  StatisticalTransferReport.fromJson(Map<String, dynamic> json) {
    orderId = json['order_id']?.toString();
    targetNumber = json['target_number']?.toString();
    sourceNumber = json['source_number']?.toString();
    money = json['money']?.toDouble();
    bank = json['bank']?.toString();
    channel = json['channel']?.toString();
    timestamp = json['timestamp']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['order_id'] = orderId;
    data['target_number'] = targetNumber;
    data['source_number'] = sourceNumber;
    data['money'] = money;
    data['bank'] = bank;
    data['channel'] = channel;
    data['timestamp'] = timestamp;
    return data;
  }
}
