///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class StatisticalTransferReportData {
/*
{
  "order_id": "333333333",
  "target_number": "1000",
  "source_number": "222222222",
  "money": 10011.6,
  "bank": "ABC",
  "channel": "t1",
  "timestamp": 10000000000
} 
*/

  String? orderId;
  String? targetNumber;
  String? sourceNumber;
  double? money;
  String? bank;
  String? channel;
  int? timestamp;

  StatisticalTransferReportData({
    this.orderId,
    this.targetNumber,
    this.sourceNumber,
    this.money,
    this.bank,
    this.channel,
    this.timestamp,
  });
  StatisticalTransferReportData.fromJson(Map<String, dynamic> json) {
    orderId = json['order_id']?.toString();
    targetNumber = json['target_number']?.toString() ?? '';
    sourceNumber = json['source_number']?.toString() ?? '';
    money = json['money']?.toDouble();
    bank = json['bank']?.toString();
    channel = json['channel']?.toString() ?? '';
    timestamp = json['timestamp']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['order_id'] = orderId;
    data['target_number'] = targetNumber;
    data['source_number'] = sourceNumber;
    data['money'] = money;
    data['bank'] = bank;
    data['channel'] = channel;
    data['timestamp'] = timestamp;
    return data;
  }
}

class StatisticalTransferReport {
/*
{
  "data": [
    {
      "order_id": "333333333",
      "target_number": "1000",
      "source_number": "222222222",
      "money": 10011.6,
      "bank": "ABC",
      "channel": "t1",
      "timestamp": 10000000000
    }
  ]
} 
*/

  List<StatisticalTransferReportData?>? data;

  StatisticalTransferReport({
    this.data,
  });
  StatisticalTransferReport.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <StatisticalTransferReportData>[];
      v.forEach((v) {
        arr0.add(StatisticalTransferReportData.fromJson(v));
      });
      data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['data'] = arr0;
    }
    return data;
  }
}
